### ISSUE TITLE
Doesn't work on Mac

### ISSUE THREAD

**Issue by scheibinger** [pranavjha/karma-optimizer#1]
When I try to add karma-optimizer it's failing when compiling one of the dependency which is `execSync`.
According to their documentation `execSync` is not really a stable module.

Here is the console output with the compilation error:
```
> execSync@1.0.2 install /Users/rscheibinger/code/mobileweb/mwnodejs/node_modules/karma-optimizer/node_modules/execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2]
    Native code compile failed!!

> phantomjs@1.9.16 install /Users/rscheibinger/code/mobileweb/mwnodejs/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
> node install.js
```

I'm wondering why there is a need for using this `execSync` external dependency while we have `execSync` method being implemented in the latest nodejs child process api: https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options

**Comment by scheibinger** [comment]
I fixed the problem mentioned above in the following pull request: https://github.com/lasso-js/karma-lasso/pull/1

**Comment by pranavjha** [comment]
@scheibinger Thanks you for the comments. I cannot use child_process.execSync because it was introduced in v0.12. Will break for earlier versions. However shelljs looks like a better alternate to execSync. updated the code to use shellJS instead of execSync.
